spring.application.name=smart-life-manager
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/smart_life?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345678}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.mail.host=${SMARTLIFE_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SMARTLIFE_MAIL_PORT:587}

# TODO: Put your Gmail Address here to send OTPs (Set this via environment variable)
spring.mail.username=${SMARTLIFE_MAIL_USERNAME:your_email@gmail.com}
# TODO: Put your Gmail 16-character App Password here (NOT your normal password, set via environment variable)
spring.mail.password=${SMARTLIFE_MAIL_PASSWORD:your_16_digit_app_password}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
smartlife.mail.enabled=true
